name: remote ssh command
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Start
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          command_timeout: 5m
          script: |
            node -v
            nvm use 14.17.0
            cd /www/wwwroot/my-react-learning
            git pull
            yarn
            yarn start
